### ISSUE TITLE
Arfhe Wallet

### ISSUE THREAD

**Issue by justbiar** [zama-ai/bounty-and-grant-program#120] opened 2024-05-08 11:01 UTC
# Zama Grant Program: Application

Please give us as much information as possible on the project you would like to submit. You can find inspiration from our existing list of grants.

- Library targeted:fhEVM

- Overview: Arfhe wallet is being developed to provide asset transfer and storage for users across the FHE ecosystem

- Description:  Unlike many wallets, Arfhe wallet aims to offer a simple interface for the end user. The networks it will support will be blockchains built on FHE. Once the development of NFT protocols on FHE is realized, Arfhe wallet will be able to be used as a profile photo on Arfhe wallet, i.e. Arfhe wallet will offer the possibility to store and transfer assets within NFT.

- Reward: 50,000 $

- Related links and reference: https://www.arfdao.com/s-projects-basic

**Comment by aquint-zama** [comment] 2024-05-10 07:31
duplicate of #117

**Closed by aquint-zama** 2024-05-10 07:31 UTC
Labels: 📄 Grant application

**Comment by justbiar** [comment] 2024-05-10 08:15
I'm sorry, I was developing this project on my own, but I brought in new developers and teammates and then I applied for a grant. I apologize again for repeating it twice.

**Comment by aquint-zama** [comment] 2024-05-10 08:24
No problem, it's just easier to track if it's one issue.

**Comment by justbiar** [comment] 2024-05-10 16:53
I closed the first issue I applied for
